version: 2.1

executors:
  standard-node:
    docker:
      - image: "cimg/node:18.14.2"
  puppeteer-node:
    docker:
      - image: "cimg/node:18.14.2-browsers"

jobs:
  setup:
    executor: standard-node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
  jest-ui-components:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test
  jest-ui-components-a11y:
    executor: puppeteer-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:a11y
  build-uic:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - setup
      - jest-ui-components:
          requires:
            - setup
      - jest-ui-components-a11y:
          requires:
            - setup
      - build-uic:
          requires:
            - setup
