version: "3.7"

services:
  sites-public:
    container_name: sites-public
    build:
      context: .
      dockerfile: Dockerfile.sites-public
      target: development
    volumes:
      - ./sites/public:/usr/src/app/sites/public
      - /usr/src/app/node_modules
      - /usr/src/app/sites/public/node_modules
    ports:
      # TODO: configure via .env separate from ./sites/public/.env
      - "3000:3000"
    env_file:
      - ./sites/public/.env
    environment:
      # The URLs are different here because requests made using BACKEND_API_BASE are done from
      # the NextJS server, which must address other containers by container name. Requests made
      # using INCOMING_HOOK_BODY are done from the client side browser and must use localhost.
      BACKEND_API_BASE: "http://backend-core:3100"
      INCOMING_HOOK_BODY: "http://localhost:3100"
      NEXTJS_PORT: "3000"
    command: yarn dev
    depends_on:
      - backend-core
    networks:
      - frontend
  sites-partners:
    container_name: sites-partners
    build:
      context: .
      dockerfile: Dockerfile.sites-partners
      target: development
    volumes:
      - ./sites/partners:/usr/src/app/sites/partners
      - /usr/src/app/node_modules
      - /usr/src/app/sites/partners/node_modules
    ports:
      # TODO: configure via .env separate from ./sites/partners/.env
      - "3001:3001"
    env_file:
      - ./sites/partners/.env
    environment:
      # Using this as the BASE works here because all requests are sent from the client's browser
      # (not the NextJS server).
      BACKEND_API_BASE: "http://localhost:3100"
      NEXTJS_PORT: "3001"
    # yarn dev uses a separate node debugger port
    command: yarn next -p 3001
    depends_on:
      - backend-core
    networks:
      - frontend
  backend-core:
    container_name: backend-core
    build:
      context: ./backend/core
      target: development
    volumes:
      - ./backend/core:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # TODO: configure 3100 via .env separate from ./backend/core/.env
      - "3100:3100"
      # This is the debug port.
      - "9229:9229"
    networks:
      - frontend
      - backend
    command: /bin/sh -c "yarn db:migration:run && yarn nest start --debug"
    env_file:
      - ./backend/core/.env
    # Override database connections to point to the container instead of localhost.
    environment:
      POSTGRES_USER: "postgres"
      DATABASE_URL: "postgres://postgres:5432/bloom"
      REDIS_TLS_URL: "redis://redis:6379/0"
      REDIS_URL: "redis://redis:6379/0"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      PGDATABASE: "bloom"
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bloom"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
volumes:
  pgdata:
networks:
  frontend:
  backend:
