version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      # Retag these images to the expected run tag to promote them as the new version

      # Backend
      - bash ./ci/scripts/retag_image.sh ${ECR_NAMESPACE}/backend "run-${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}" run
      - bash ./ci/scripts/retag_image.sh ${ECR_NAMESPACE}/backend "migrate-${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}" migrate

      # Public site
      #- bash ./ci/scripts/retag_image.sh ${ECR_NAMESPACE}/public run-candidate run

      # Partner site
      #- bash ./ci/scripts/retag_image.sh ${ECR_NAMESPACE}/partners run-candidate run

      # Import listings task
      - bash ./ci/scripts/retag_image.sh ${ECR_NAMESPACE}/import-listings "${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}" run
