version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0

executors:
  standard-node:
    docker:
      - image: "cimg/node:18.14.2"
      - image: "cimg/postgres:12.10"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom
  cypress-node:
    docker:
      - image: "cypress/base:18.14.1"
      - image: "cimg/postgres:12.10"
        environment:
          POSTGRES_USER: bloom-ci
          # Never do this in production or with any sensitive / non-test data:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bloom
    environment:
      PORT: "3100"
      EMAIL_API_KEY: "SG.SOME-LONG-SECRET-KEY"
      APP_SECRET: "CI-LONG-SECRET-KEY"
      # DB URL for migration and seeds:
      DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
      # DB URL for the jest tests per ormconfig.test.ts
      TEST_DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
      PARTNERS_PORTAL_URL: "http://localhost:3001"

jobs:
  setup:
    executor: standard-node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
  setup-with-db:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:backend:core:dbsetup
  lint:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint
  jest-shared-helpers:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:shared:helpers
  jest-backend:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: DB Setup + Backend Core Tests
          command: |
            yarn test:backend:core:dbsetup
            yarn test:backend:core
            yarn test:e2e:backend:core
          environment:
            PORT: "3100"
            EMAIL_API_KEY: "SG.SOME-LONG-SECRET-KEY"
            APP_SECRET: "CI-LONG-SECRET-KEY"
            # DB URL for migration and seeds:
            DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
            # DB URL for the jest tests per ormconfig.test.ts
            TEST_DATABASE_URL: "postgres://bloom-ci@localhost:5432/bloom"
            CLOUDINARY_SIGNED_PRESET: "fake_secret"
            CLOUDINARY_KEY: "fake_key"
            CLOUDINARY_CLOUD_NAME: "exygy"
            CLOUDINARY_SECRET: "fake_secret"
            PARTNERS_PORTAL_URL: "http://localhost:3001"
  build-public:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:public
  build-partners:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build:app:partners
  unit-test-partners:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:app:partners:unit
  unit-test-public:
    executor: standard-node
    steps:
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test:app:public:unit

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - jest-shared-helpers:
          requires:
            - setup
      - jest-backend:
          requires:
            - setup
      - build-public:
          requires:
            - setup
      - unit-test-public:
          requires:
            - setup
      - build-partners:
          requires:
            - setup
      - unit-test-partners:
          requires:
            - setup
      - cypress/run:
          name: "cypress-public"
          requires:
            - setup
          executor: cypress-node
          working_directory: sites/public
          yarn: true
          build: |
            yarn test:backend:core:dbsetup
          start: yarn dev:all-cypress
          wait-on: "http://0.0.0.0:3000"
          store_artifacts: true
      - cypress/run:
          name: "cypress-partners"
          requires:
            - setup
          executor: cypress-node
          working_directory: sites/partners
          yarn: true
          build: |
            echo 'export FEATURE_LISTINGS_APPROVAL=FALSE' >> "$BASH_ENV"
            source "$BASH_ENV"
            yarn test:backend:core:dbsetup
          start: |
            yarn dev:all-cypress
          command: |
            npx cypress run --spec cypress/e2e/default/**/*.{js,jsx,ts,tsx}
          wait-on: "http://0.0.0.0:3001"
          store_artifacts: true
      - cypress/run:
          name: "cypress-partners-listings-approval"
          requires:
            - setup
          executor: cypress-node
          working_directory: sites/partners
          yarn: true
          build: |
            echo 'export FEATURE_LISTINGS_APPROVAL=TRUE' >> "$BASH_ENV"
            source "$BASH_ENV"
            yarn test:backend:core:dbsetup
          start: |
            yarn dev:all-cypress
          command: |
            npx cypress run --spec cypress/e2e/listings-approval/**/*.{js,jsx,ts,tsx}
          wait-on: "http://0.0.0.0:3001"
          store_artifacts: true
