# AWS CodeBuild config
# This file is referenced in the infra repo as a CodeBuild buildspec target.

# These 3 variables are set in the codebuild project definition's environment secion.
# ECR_REGION
# ECR_ACCOUNT_ID
# ECR_NAMESPACE

version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - aws ecr get-login-password --region "${ECR_REGION}" | docker login --username AWS --password-stdin "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com"

  build:
    commands:
      # Backend
      - docker build backend/core -f build/docker/Dockerfile.backend --target tests -t backend/core:test
      - docker run backend/core:test yarn test
      - docker build backend/core -f build/docker/Dockerfile.backend --target run -t backend/core:run
      - docker tag backend/core:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/backend:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker tag backend/core:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/backend:latest"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/backend:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/backend:latest"

      # Partners
      - docker build . -f build/docker/Dockerfile.sites-generic --target test --build-arg partners -t sites/partners:test
      ## Failing with https://gist.github.com/isaac-looker/537a7eec3fb9ba79f022d9fc99712572
      # - docker run sites/partners:test
      - docker build . -f build/docker/Dockerfile.sites-generic --target test --build-arg partners -t sites/partners:run
      - docker tag  sites/partners:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/partners:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker tag  sites/partners:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/partners:latest"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/partners:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/partners:latest"

      # Public
      - docker build . -f build/docker/Dockerfile.sites-generic --target test --build-arg public -t sites/public:test
      ## Failing with https://gist.github.com/isaac-looker/08fd16b80092437d58a5e36e299bccd3
      # - docker run sites/public:test
      - docker build . -f build/docker/Dockerfile.sites-generic --target run --build-arg public -t sites/public:run
      - docker tag sites/public:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/public:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker tag sites/public:run "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/public:latest"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/public:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
      - docker push "${ECR_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_NAMESPACE}/public:latest"
