# AWS CodeBuild config
# This file is referenced in the infra repo as a CodeBuild buildspec target.

# This 1 variable is set in the codebuild project definition's environment secion.
# SDLC_STAGE

version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 16

  build:
    commands:
      - aws ecs update-service --force-new-deployment --cluster "doorway-${SDLC_STAGE}-srv-backend" --service "doorway-${SDLC_STAGE}-srv-backend"
      - aws ecs update-service --force-new-deployment --cluster "doorway-${SDLC_STAGE}-srv-public" --service "doorway-${SDLC_STAGE}-srv-public"
      - aws ecs update-service --force-new-deployment --cluster "doorway-${SDLC_STAGE}-srv-partner" --service "doorway-${SDLC_STAGE}-srv-partner"
