import {
  AlternateContactRelationship,
  Application,
  ApplicationReviewStatusEnum,
  ApplicationStatusEnum,
  ApplicationSubmissionTypeEnum,
  HouseholdMemberRelationship,
  IncomePeriodEnum,
  LanguagesEnum,
  UnitTypeEnum,
  YesNoEnum,
} from "../types/backend-swagger"

export const filledApplication: Application = {
  id: "1234",
  createdAt: new Date(),
  updatedAt: new Date(),
  contactPreferences: [],
  status: ApplicationStatusEnum.draft,
  submissionType: ApplicationSubmissionTypeEnum.electronical,
  markedAsDuplicate: false,
  confirmationCode: "1234",
  applicationLotteryPositions: [],
  applicant: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstName: "applicant first name",
    middleName: "applicant middle name",
    lastName: "applicant last name",
    birthMonth: "12",
    birthDay: "17",
    birthYear: "1993",
    emailAddress: "example@email.com",
    noEmail: false,
    phoneNumber: "111-111-1111",
    phoneNumberType: "Cell",
    noPhone: false,
    workInRegion: YesNoEnum.yes,
    applicantWorkAddress: {
      id: "1234",
      createdAt: new Date(),
      updatedAt: new Date(),
      street: "1234",
      street2: "1234",
      city: "1234",
      state: "CA",
      zipCode: "12345",
    },
    applicantAddress: {
      id: "1234",
      createdAt: new Date(),
      updatedAt: new Date(),
      street: "1234",
      street2: "1234",
      city: "1234",
      state: "CA",
      zipCode: "12345",
    },
  },
  accessibility: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    mobility: false,
    vision: false,
    hearing: false,
  },
  alternateContact: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    type: AlternateContactRelationship.other,
    otherType: "example other type",
    firstName: "example first name",
    lastName: "example last name",
    agency: "example agency",
    phoneNumber: "111-111-1111",
    emailAddress: "example@email.com",
    address: {
      id: "1234",
      createdAt: new Date(),
      updatedAt: new Date(),
      street: "1234",
      street2: "1234",
      city: "1234",
      state: "CA",
      zipCode: "12345",
    },
  },
  applicationsAlternateAddress: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    street: "1234",
    street2: "1234",
    city: "1234",
    state: "CA",
    zipCode: "12345",
  },
  applicationsMailingAddress: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    street: "1234",
    street2: "1234",
    city: "1234",
    state: "CA",
    zipCode: "12345",
  },
  listings: {
    id: "1234",
  },
  demographics: {
    id: "1234",
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "example gender",
    sexualOrientation: "example sexual orientation",
    howDidYouHear: ["example how did you hear"],
    race: ["example race"],
    spokenLanguage: "example language",
    ethnicity: "example",
  },
  preferredUnitTypes: [
    {
      createdAt: new Date(),
      updatedAt: new Date(),
      id: "1234",
      name: UnitTypeEnum.oneBdrm,
      numBedrooms: 2,
    },
  ],
  householdMember: [
    {
      createdAt: new Date(),
      updatedAt: new Date(),
      id: "1234",
      orderId: 0,
      firstName: "example first name",
      middleName: "example middle name",
      lastName: "example last name",
      birthMonth: "12",
      birthDay: "17",
      birthYear: "1993",
      sameAddress: YesNoEnum.yes,
      relationship: HouseholdMemberRelationship.brotherSister,
      workInRegion: YesNoEnum.yes,
      householdMemberWorkAddress: {
        id: "1234",
        createdAt: new Date(),
        updatedAt: new Date(),
        street: "1234",
        street2: "1234",
        city: "1234",
        state: "CA",
        zipCode: "12345",
      },
      householdMemberAddress: {
        id: "1234",
        createdAt: new Date(),
        updatedAt: new Date(),
        street: "1234",
        street2: "1234",
        city: "1234",
        state: "CA",
        zipCode: "12345",
      },
    },
  ],
  appUrl: "http://www.example.com",
  additionalPhone: true,
  additionalPhoneNumber: "111-111-1111",
  additionalPhoneNumberType: "example additional phone number type",
  householdSize: 2,
  housingStatus: "example housing status",
  sendMailToMailingAddress: true,
  householdExpectingChanges: false,
  householdStudent: false,
  incomeVouchers: ["1234"],
  income: "36000",
  incomePeriod: IncomePeriodEnum.perYear,
  language: LanguagesEnum.en,
  acceptedTerms: true,
  submissionDate: new Date(),
  reviewStatus: ApplicationReviewStatusEnum.valid,
}
